### ISSUE TITLE
Enable recovery mode in case of a failure

### ISSUE THREAD

**Issue by MathildeFranconRTE** [AntaresSimulatorTeam/antares-xpansion#206]
Export information from the last **master problem** in order to  : 

-  enable a "**recovery**" mode in case of failure.
-  enable sensitivity studies to be carried out

**Comment by tbittar** [comment]
Now, the master problem is written to a mps file after each iteration. From a mathematical point of view, we have all the data to perform a restart from the last iteration. Indeed, resuming the run simply consists in launching the Benders step with the initial master problem being read from `master_last_iteration.mps`.

From the IT point of view several points need attention :

- We can have a `--resume` flag to resume an previously interrupted run of Xpansion, that will read `master_last_iteration.mps` instead of `master.mps`. We can either set in the Python driver the steps that are launched (benders and potentially study_update) or explicitly specify the Benders step flag in command line.

- When initializing the `WorkerMaster` from `master_last_iteration.mps`:
   - `set_upper_bounds()` is useless as it has already be done in the initial run and `master_last_iteration.mps` takes into account the result of this method.
   - `add_alpha_var()` needs to be modified. This method consists in adding the columns corresponding to the `alpha` and `alpha_i` variables and sets the `_id_alpha` and `_id_alpha_i` attributes.
       - As the columns are already present in `master_last_iteration.mps` there is no need to add the columns again in the `--resume` case.
       - However, the `_id_alpha` and `_id_alpha_i` attributes still need to be correctly set, so we must find a way to find their id while reading the `master_last_iteration.mps` file. The current way of finding these id consists in iteratively adding a column and counting the number of columns in the master problem. This method is not valid for a restart as all columns have already been added.
 - The option `BOUND_ALPHA` may be deactivated as its effect is already present in the `master_last_iteration.mps`.
 - Check the behaviour if the execution stops before the end of iteration 1, is the `master_last_iteration.mps` saved ? Useful ? Should we resume the benders step as it there were no restart ?
 - Think about the modification of the options when resuming (number of max iterations, timelimit).

**Comment by tbittar** [comment]
For this feature, there are two possible use cases :
 1. The study stopped because of a crash / maintenance of the server.
 2. The study ran normally but the user wants to run some more iterations to improve convergence.

The behaviour should be the following :

After the initial run, we store the number of iterations and time spent on the study. Then, upon restart the iteration counter and resolution time start from the stored data. Thus :
 1. In case of a crash, the user does not change anything in his study. The study can then be completed normally with the number of iterations and time limit initially set.
 2. If the user wants to add more iterations or allow more time, he must change the `settings.ini` file and set the `timelimit` and/or `max-iteration` fields to the **cumulated** parameters he wants. Then, the parameters of the `settings.ini` file will represent the **total** number of iterations / time spent on the study.
 For example : A study was set up with `max-iteration = 30` and stopped because this max number was reached. If the user wants to add 10 more iterations, he must set `max-iteration = 40` so that the 40 iterations will represent the total number of iterations from both the initial run and the restart.
