### ISSUE TITLE
The GUI is not working on Ubuntu

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#294]
When launching a study from the GUI on Ubuntu (launched from the executable `antares-xpansion-ui`, nothing happens (no messages, no errors). 

However, the GUI is running normally when launched with the Python launcher using `python antares-xpansion-ui.py`

**Comment by a-zakir** [comment]
hello,
- it seems there are some troubles in PyQt5 package installed with pip in ubuntu :
 at the end of build step I have theses messages : 
`WARNING: Cannot find libQt5EglFSDeviceIntegration.so.5 `
`WARNING: Cannot find libxcb-xinerama.so.0 (needed by /ho`
`WARNING: Cannot find libxcb-xinerama.so.0 (needed by /ho`
`WARNING: Cannot find libQt5EglFSDeviceIntegration.so.5 (`
`WARNING: Cannot find libQt5EglFSDeviceIntegration.so.5 (`
`WARNING: Cannot find libQt5EglFsKmsSupport.so.5 (needed `
`WARNING: Cannot find libxcb-xinerama.so.0 (needed by /ho`
`WARNING: Cannot find libxcb-xinerama.so.0 (needed by /ho`
`WARNING: Cannot find libxcb-xinerama.so.0 (needed by /ho`
`WARNING: Cannot find libxcb-xinerama.so.0 (needed by /ho`
`WARNING: Cannot find libQt5EglFSDeviceIntegration.so.5 (`
`WARNING: Cannot find libicudata.so.56 (needed by /home/b`
`WARNING: Cannot find libicuuc.so.56 (needed by /home/bar`
`WARNING: Cannot find libicudata.so.56 (needed by /home/b`
`WARNING: Cannot find libxcb-xinerama.so.0 (needed by /ho`
**wich logically lead to an error when executing `antares-xpansion-ui`** : 

`qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
Abandon (core dumped)` (see full [log.txt](https://github.com/AntaresSimulatorTeam/antares-xpansion/files/7624805/log.txt)  debug message obtained with export `QT_DEBUG_PLUGINS=1`)

a cleaner version of Pyqt5 for ubuntu is given via the official ubuntu package : `sudo apt install python3-pyqt5`
see [https://doc.ubuntu-fr.org/pyqt](https://doc.ubuntu-fr.org/pyqt)

- With a successful installation,  there is a bug at run time. Nothing happens when `run` button is clicked.
pr #297 will fix it.
[log.txt](https://github.com/AntaresSimulatorTeam/antares-xpansion/files/7624805/log.txt)
