### ISSUE TITLE
Unable to use max number of processes with MPI on some studies

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#301]
When launching small studies, such as the examples, I am unable to use the 8 cores of my machine. For example, on `data_test/examples/xpansion-test-01`, the MPI version of Benders works on 4 cores but not with more than 4.

From what I understood from @sgatto , if the Antares-Xpansion problem has `n-1` slaves, the problem can run on at most `n` cores. So with less than 7 slaves, MPI Benders will fail if launched with 8 cores. This behavior must be changed in order to avoid the crash.

This is particularly annoying for the user experience, as the number of available is indicated on the graphical user interface.

**Comment by sgatto** [comment]
After investigation:
The problem is independent from the study. It comes from the interaction between way we check the number of availables cores in the GUI and the installation of MPI on different machines.

The openmpi installation on Ubuntu sets the number of availables slots (max number of MPI procs) to the number of physical, not logical, cores.
With an Intel CPU with 4 physical cores/8 threads

`os.cpu_count()` returns 8
While OpenMPI is set, during installation, with 4 slots onlt (physical cores). This configuration is good since it maximises the performances
Running Xpansion on 8 procs is stopped by openmpi (on Ubuntu) with message
```
There are not enough slots available in the system to satisfy the 8
slots that were requested by the application:*
...
```

We will change the way we veryfy the number of available cores by using `psutil.cpu_count(logical=False)` (thanks @tbittar )
