### ISSUE TITLE
Clean and uniformize output file extensions

### ISSUE THREAD

**Issue by tbittar** [AntaresSimulatorTeam/antares-xpansion#345]
Antares-Xpansion produces several output files that are stored in the `output/<simulation_name>/lp` or in `output/<simulation_name>`. They are all text/log files but have different extensions. Here are the concerned files with proposed fix.
- `reportbenderssequential` (no extension) when running a sequential simulation -> add `txt` extension
- `reportbendersmpi.txt` when running a mpi simulation -> ok
- `bendersmpi.INFO`, `benderssequential.INFO` -> change to `txt` extension
- `benderssequentialLog<timestamp>` (idem with mpi) which is actually the same file as `benderssequential.INFO` (idem with mpi) -> check that it is indeed the same as `benderssequential.INFO` and remove file if it is so  
- `lp_namer.log` on Linux and `lp_namer.exe.log` on Windows -> change to `lp_namer.log` on Windows

**Comment by a-zakir** [comment]
Hello,

Point 1 and 2 and the last one are fixed in PR #346 .
regarding files `fileName<timestamp>`, in the code we only indicate the file name part and google api for logging append the timestamp the reason is to  **write "message[0,message_len-1]" corresponding to an event that occurred at "timestamp"** .
The `.INFO` files are **symlink to the latest log file** e.g to the latest `fileName<timestamp>`. 
see [glog/logging.h](https://github.com/google/glog/blob/master/src/glog/logging.h.in)
those files are not created on windows platforms.
