### ISSUE TITLE
Logger for problem_generation

### ISSUE THREAD

**Issue by a-zakir** [AntaresSimulatorTeam/antares-xpansion#509]
For now log messages from problem_generation step are  catched only by the python orchestrator and redirected to a file.
I think it would be interesting to create a logger in problem_generation's c++ lib.
or maybe a unique logger for all xpansion.

**Comment by tbittar** [comment]
I do not know if this comment is appropriate here, but today, the logs of the antares step and the problem_generation step generated by the Python driver (such as the execution time of the step) are not printed to a file, which makes it difficult to retrieve the information after the run is completed. 

Should we open a dedicated issue ? Or think more globally about the way the logs are handled in Xpansion ?

**Comment by a-zakir** [comment]
for problem_generation, there is a log file generated `lp_namer.log`. it contains outputs of lp_namer exe.
Antares step produce also a file, `simulation.log`

**Comment by tbittar** [comment]
Yes I agree, but some outputs are generated by `antares_driver.py` and `problem_generation_driver.py`. These outputs are not captured in the log files (that capture the C++ output). 

In fact the most interesting output from Python is the execution time of the step, but it could well be computed from the C++ code as well so that it appears in `lp_namer.log` for problem_generation (more complicated for antares)
